version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  odoo:
    image: odoo:16.0
    depends_on:
      - postgres
    ports:
      - '8069:8069'
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo-config:/etc/odoo
    command: ['--', '--init=base']

volumes:
  odoo-web-data:
  odoo-db-data:
