/**
 * Outputs Tab
 * Files and outputs generated by this workflow
 */

interface OutputsTabProps {
  workflow: any;
}

export default function OutputsTab({ workflow }: OutputsTabProps) {
  const outputs = [
    {
      id: '1',
      fileName: 'daily-sales-report-2024-01-16.pdf',
      type: 'report',
      size: 2450000,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      url: '#',
    },
    {
      id: '2',
      fileName: 'daily-sales-report-2024-01-15.pdf',
      type: 'report',
      size: 2380000,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      url: '#',
    },
    {
      id: '3',
      fileName: 'daily-sales-report-2024-01-14.pdf',
      type: 'report',
      size: 2420000,
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      url: '#',
    },
  ];

  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  };

  return (
    <div className='space-y-6'>
      {/* Summary Stats */}
      <div className='grid grid-cols-1 md:grid-cols-3 gap-4'>
        <div className='bg-gradient-to-br from-blue-600/20 to-cyan-600/20 backdrop-blur-sm border border-blue-500/20 rounded-xl p-4'>
          <p className='text-gray-300 text-sm mb-1'>Toplam Çıktı</p>
          <p className='text-2xl font-bold text-white'>{outputs.length}</p>
        </div>
        <div className='bg-gradient-to-br from-purple-600/20 to-pink-600/20 backdrop-blur-sm border border-purple-500/20 rounded-xl p-4'>
          <p className='text-gray-300 text-sm mb-1'>Toplam Boyut</p>
          <p className='text-2xl font-bold text-white'>
            {formatFileSize(outputs.reduce((acc, o) => acc + o.size, 0))}
          </p>
        </div>
        <div className='bg-gradient-to-br from-green-600/20 to-emerald-600/20 backdrop-blur-sm border border-green-500/20 rounded-xl p-4'>
          <p className='text-gray-300 text-sm mb-1'>Son Çıktı</p>
          <p className='text-white font-medium text-sm truncate'>
            {outputs[0]?.fileName}
          </p>
        </div>
      </div>

      {/* Outputs List */}
      <div className='bg-gradient-to-br from-gray-800/50 to-gray-900/50 backdrop-blur-sm border border-white/10 rounded-xl p-6'>
        <div className='flex items-center justify-between mb-4'>
          <h3 className='text-lg font-semibold text-white flex items-center gap-2'>
            <i className='ri-folder-download-line'></i>
            Üretilen Dosyalar
          </h3>
          <button className='bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2'>
            <i className='ri-download-line'></i>
            Hepsini İndir (ZIP)
          </button>
        </div>

        <div className='space-y-3'>
          {outputs.map(output => (
            <div
              key={output.id}
              className='flex items-center gap-4 p-4 bg-gray-800/30 rounded-lg hover:bg-gray-800/50 transition-colors'
            >
              {/* Icon */}
              <div className='w-12 h-12 bg-gradient-to-r from-blue-500 to-cyan-500 rounded-lg flex items-center justify-center'>
                <i className='ri-file-pdf-line text-white text-xl'></i>
              </div>

              {/* Info */}
              <div className='flex-1'>
                <h4 className='text-white font-medium text-sm mb-1'>
                  {output.fileName}
                </h4>
                <div className='flex items-center gap-3 text-xs text-gray-400'>
                  <span>{formatFileSize(output.size)}</span>
                  <span>•</span>
                  <span>
                    {new Date(output.createdAt).toLocaleDateString('tr-TR')}
                  </span>
                </div>
              </div>

              {/* Actions */}
              <div className='flex gap-2'>
                <button className='bg-indigo-600/20 hover:bg-indigo-600/30 text-indigo-400 px-3 py-2 rounded-lg text-xs font-medium transition-colors flex items-center gap-1'>
                  <i className='ri-eye-line'></i>
                  Önizle
                </button>
                <button className='bg-green-600/20 hover:bg-green-600/30 text-green-400 px-3 py-2 rounded-lg text-xs font-medium transition-colors flex items-center gap-1'>
                  <i className='ri-download-line'></i>
                  İndir
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Export Options */}
      <div className='bg-gradient-to-br from-gray-800/50 to-gray-900/50 backdrop-blur-sm border border-white/10 rounded-xl p-6'>
        <h3 className='text-lg font-semibold text-white mb-4 flex items-center gap-2'>
          <i className='ri-share-line'></i>
          Dışa Aktarma Seçenekleri
        </h3>
        <div className='grid grid-cols-1 md:grid-cols-3 gap-3'>
          <button className='bg-gray-800/50 hover:bg-gray-800 text-white px-4 py-3 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-2'>
            <i className='ri-mail-line'></i>
            E-posta ile Gönder
          </button>
          <button className='bg-gray-800/50 hover:bg-gray-800 text-white px-4 py-3 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-2'>
            <i className='ri-cloud-line'></i>
            Cloud Storage'a Kaydet
          </button>
          <button className='bg-gray-800/50 hover:bg-gray-800 text-white px-4 py-3 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-2'>
            <i className='ri-share-forward-line'></i>
            Paylaşım Linki Oluştur
          </button>
        </div>
      </div>
    </div>
  );
}
